# Netlify configuration file
# This handles client-side routing for React Router

[build]
  publish = "dist"
  command = "npm run build"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200